pebfit/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'workouts' => 'workouts#view'
  get 'calendars' => 'calendars#view'

end

pebfit/app/models/activity.rb
class Activity < ActiveRecord::Base
end

pebfit/app/models/theworkout.rb
class Theworkout < ActiveRecord::Base
end

pebfit/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

pebfit/app/models/workout.rb
class Workout < ActiveRecord::Base
end

pebfit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    # TODO: redirect user to work-outs
  end

end

pebfit/app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

    def view
    end

end

pebfit/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
	end

	def contact
	end

end

pebfit/app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def view
  end

  def show
  end

  def new
  end

  def delete
  end

end

pebfit/app/helpers/application_helper.rb
module ApplicationHelper
end

pebfit/app/helpers/calendars_helper.rb
module CalendarsHelper
end

pebfit/app/helpers/home_helper.rb
module HomeHelper
end

pebfit/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

pebfit/app/views/calendars/view.html.erb
<h1>this is the Calendar page</h1>

pebfit/app/views/home/about.html.erb
<h1>About page</h1>

pebfit/app/views/home/contact.html.erb
<h1>contacts</h1>

pebfit/app/views/home/index.html.erb
<div class="homepage-header">
  <div>
    <h1>Home</h1>
    <div class="jumbotron">
      <h2>Time your workout, Track your progress</h2>
      <p>Do you have a pebble watch?</p>
      <p>Don't want to cover your phone with sweat?</p>
      <p> Can't be bothered clicking your phone every 20 or so seconds?</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Use PebFit!</a></p>
  </div>
  <div>
</div>

pebfit/app/views/layouts/_header.html.erb
  <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">PebFit</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a <%= link_to "Home", root_path %> </li>
              <li> <%= link_to "About", about_path %> </li>
              <li> <%= link_to "Contact", contact_path %> <li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

              <% if user_signed_in? %>

                <li> <%= link_to "Workouts", workouts_path %> </li>
                <li> <%= link_to "Calender", calendars_path %> </li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                </ul>

              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                 <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>

              <% end %>


            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

pebfit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pebfit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
</script>
<div class="row">
	<div class="container">
    <div class="col-md-offset-2 col-md-8">
		  <% if notice %>
			<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			<p class="alert alert-danger"><%= alert %></p>
			<% end %>

			<%= yield %>
		</div>
	</div>
</div>
</body>

</html>

pebfit/app/views/workouts/_activity_row.html.erb
<tr>
  <div class="row">
 	 <td><%= activity.activity %></td>
  	 <td><%= activity.lengthInSeconds %></td>
  	 <td><a href="#">Delete</a></td>
  </div>

</tr>

pebfit/app/views/workouts/_workout_row.html.erb
<tr>
  <td><%= workout.name %></td>

  <td><%= workout.totaltime %></td>
  <td><%= workout.lastattempt %></td>

  <td><%= link_to "Show", workout_path(workout) %> | <%= link_to "Delete", workouts_path, method: :delete %></td>
</tr>

pebfit/app/views/workouts/new.html.erb
 <h2 class='page-header'>New Workout</h2>

    <%= form_for @workout, url: { action: "create" } do |f| %>

      <% if @workout.errors.any? %>
        <div class="panel panel-danger">
          <div class="panel-heading">
            Something went wrong <strong>(ノಠ益ಠ)ノ彡┻━┻</strong>
          </div>
          <div class="panel-body">
            <ul>
              <% @workout.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      </div>
      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>

pebfit/app/views/workouts/show.html.erb
    <h2 class='page-header'><%= @workout.name %></h2>
    
    
      <p><strong>Here is the workout you have already created :</strong> </p>
          
    
    <table class='table'>
	<thead>
        <tr>
          
          <th>Activity</th>
          <th>Time in seconds</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @activities.each do |p| %>
          <%= render "activity_row", activity: p %>
        <% end %>
      </tbody>
     </table>
    <hr>
<a class="btn btn-primary" href="#">Add</a>

pebfit/app/views/workouts/view.html.erb
<h1>
  View for the workouts controller
</h1>